<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{331e9dbf-c59d-4b03-a4cc-cb4fe771a8ab}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	count1 :INT;
	F1 :FBDelayCheck;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F1(in := count1, delaytime := T#0.2S);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>